### ISSUE TITLE
Add basic README and license.

### ISSUE THREAD

**Issue by youngchief-btw** [aboutdavid/website#1]
Hi, @aboutdavid. The website is starting to look really good! 

I wanted to suggest a really basic README and some form of explicit copyright disclaimer.

Thanks for listening,
--- youngchief btw ツ

**Comment by dispherical** [comment]
Alright, I've set a few things in the license
- Changes **must** be open-sourced
- In order to publish the website, a majority of the code must have been changed (I don't like people rehosting my website and just changing the name, it's really, REALLY, annoying
- Changes must be stated
- Give credit

I'll give basic things in the `README.md`, but I do not intend to offer support with setting this up.
